POST https://localhost:7106/api/sample HTTP/1.1
Host: example.com
Content-Type: application/json

{
  "data": {
    "key1": "value1",
    "key2": "value2",
    "key3": "value3"
  },
  "simpleHooksMetadata": { 
      "eventBusinessId": "123456789",
      "eventDefinitionName": "exampleEvent"
  }
}
